services:
  app:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - PURGE_INTERVAL_SECONDS=600
      - PURGE_ON_START=1

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - CHALLENGE_URL=http://nginx
      - FLAG=${FLAG}

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - app
      - bot
    ports:
      - "6767:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
